const db=window.supabaseClient;if(!db){location.replace('login.html')}
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const state={user:null,profileId:null,gtk:null,news:null,event:null,award:null,alumni:null,gallery:null,gtkRows:[],newsRows:[],eventRows:[],awardRows:[],alumniRows:[],galleryRows:[]};
const msg=(id,text,error=false)=>{const e=$(id);if(e){e.textContent=text;e.classList.toggle('error',error)}};
async function boot(){const {data,error}=await db.auth.getSession();if(error||!data.session){location.replace('login.html');return}state.user=data.session.user;await loadProfile();await Promise.all([loadGTK(),loadNews(),loadEvents(),loadAwards(),loadAlumni(),loadGallery()])}
$('logout').onclick=async()=>{await db.auth.signOut();location.replace('login.html')};
async function upload(bucket,file,prefix){if(!file)return null;if(file.size>1200000)throw new Error('File terlalu besar. Maksimal 1,2 MB.');const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');const path=`${prefix}/${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;const {error}=await db.storage.from(bucket).upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;return db.storage.from(bucket).getPublicUrl(path).data.publicUrl}
function preview(input,im){input?.addEventListener('change',()=>{const f=input.files[0];if(!f){im.style.display='none';return}if(f.size>1200000){alert('File terlalu besar. Maksimal 1,2 MB.');input.value='';return}const r=new FileReader();r.onload=()=>{im.src=r.result;im.style.display='block'};r.readAsDataURL(f)})}
preview($('pphoto'),$('photoPreview'));preview($('alumniPhoto'),$('alumniPreview'));preview($('galleryPhoto'),$('galleryPreview'));
async function loadProfile(){const {data,error}=await db.from('profil_sekolah').select('*').limit(1).maybeSingle();if(error){msg('schoolStatus','Gagal memuat profil: '+error.message,true);return}const d=data||{};state.profileId=d.id||null;[['school',d.nama_sekolah||'UPT SD Negeri 029 Bentenna'],['year',d.tahun_berdiri||1973],['students',d.peserta_didik??246],['teachers',d.jumlah_guru??15],['staff',d.jumlah_tendik??6],['rombel',d.rombel??6],['tagline',d.tagline||'Menginspirasi Negeri'],['heroText',d.hero_text||'Mendidik, membimbing, dan menginspirasi generasi penerus yang kreatif, berkarakter, berdaya saing, dan berakhlak mulia.'],['about',d.sejarah||''],['email',d.email||'uptsdnegeribentennalutra@gmail.com'],['location',d.alamat||'Kabupaten Luwu Utara, Provinsi Sulawesi Selatan, Indonesia.']].forEach(([id,v])=>$(id).value=v)}
$('schoolForm').onsubmit=async e=>{e.preventDefault();const p={nama_sekolah:$('school').value.trim(),tahun_berdiri:Number($('year').value)||1973,peserta_didik:Number($('students').value)||0,jumlah_guru:Number($('teachers').value)||0,jumlah_tendik:Number($('staff').value)||0,rombel:Number($('rombel').value)||0,tagline:$('tagline').value.trim(),hero_text:$('heroText').value.trim(),sejarah:$('about').value.trim(),email:$('email').value.trim(),alamat:$('location').value.trim(),updated_at:new Date().toISOString()};const q=state.profileId?db.from('profil_sekolah').update(p).eq('id',state.profileId):db.from('profil_sekolah').insert(p).select().single();const {data,error}=await q;if(error)return msg('schoolStatus','Gagal: '+error.message,true);if(data)state.profileId=data.id;msg('schoolStatus','✓ Identitas berhasil disimpan ke database online.')};
async function loadGTK(){const {data,error}=await db.from('gtk').select('*').eq('aktif',true).order('urutan').order('nama');if(error){msg('peopleStatus','Gagal memuat GTK: '+error.message,true);return}state.gtkRows=data||[];$('peopleList').innerHTML=state.gtkRows.length?state.gtkRows.map(p=>`<div class="item"><div class="main">${p.foto_url?`<img class="photo" src="${p.foto_url}" alt="">`:`<div class="placeholder">${p.status==='Kepala Sekolah'?'KS':p.status==='Tenaga Kependidikan'?'T':'G'}</div>`}<div><b>${esc(p.nama)}</b><span class="small">${esc(p.jabatan||'')} · ${esc(p.status||'')}${p.nip?' · '+esc(p.nip):''}</span></div></div><div class="actions"><button class="blue" onclick="editGTK('${p.id}')">✏️ Edit</button><button class="danger" onclick="deleteRow('gtk','${p.id}',loadGTK)">🗑 Hapus</button></div></div>`).join(''):'<p class="small">Belum ada data GTK.</p>'}
window.editGTK=id=>{const p=state.gtkRows.find(x=>x.id===id);if(!p)return;state.gtk=p;$('pname').value=p.nama;$('prole').value=p.jabatan||'';$('pid').value=p.nip||'';$('pstatus').value=p.status||'Guru';$('photoPreview').src=p.foto_url||'';$('photoPreview').style.display=p.foto_url?'block':'none';$('addPerson').textContent='💾 Simpan Perubahan GTK';$('cancelPerson').classList.remove('hidden');location.hash='gtk'};
function resetGTK(){state.gtk=null;['pname','prole','pid','pphoto'].forEach(id=>$(id).value='');$('photoPreview').style.display='none';$('addPerson').textContent='➕ Tambah GTK';$('cancelPerson').classList.add('hidden')}$('cancelPerson').onclick=resetGTK;
$('addPerson').onclick=async()=>{try{const file=$('pphoto').files[0];let foto_url=state.gtk?.foto_url||null;if(file)foto_url=await upload('foto-gtk',file,'gtk');const p={nama:$('pname').value.trim(),jabatan:$('prole').value.trim(),nip:$('pid').value.trim(),status:$('pstatus').value,foto_url,aktif:true};if(!p.nama||!p.jabatan)return alert('Nama dan jabatan wajib diisi.');const q=state.gtk?db.from('gtk').update(p).eq('id',state.gtk.id):db.from('gtk').insert(p);const {error}=await q;if(error)throw error;resetGTK();await loadGTK();msg('peopleStatus','✓ Data GTK tersimpan.')}catch(e){msg('peopleStatus','Gagal: '+e.message,true)}};
function rowsHTML(rows,kind){const map={news:['judul','tanggal'],events:['judul','tanggal'],awards:['judul','tahun'],alumni:['nama','tahun_lulus']};return rows.length?rows.map(x=>{let sub=x[map[kind][1]]||'';if(kind==='news'&&x.tanggal)sub=new Date(x.tanggal).toLocaleDateString('id-ID');return `<div class="item"><div><b>${esc(x[map[kind][0]])}</b><span class="small">${esc(sub)}${x.lokasi?' · '+esc(x.lokasi):''}${x.tingkat?' · '+esc(x.tingkat):''}${x.pekerjaan?' · '+esc(x.pekerjaan):''}</span></div><div class="actions"><button class="blue" onclick="${kind==='events'?'editEvent':kind==='awards'?'editAward':kind==='alumni'?'editAlumni':'editNews'}('${x.id}')">✏️ Edit</button><button class="danger" onclick="deleteRow('${kind==='events'?'kegiatan':kind==='awards'?'prestasi':kind}','${x.id}',${kind==='events'?'loadEvents':kind==='awards'?'loadAwards':kind==='alumni'?'loadAlumni':'loadNews'})">🗑 Hapus</button></div></div>`}).join(''):'<p class="small">Belum ada data.</p>'}
async function loadNews(){const {data,error}=await db.from('berita').select('*').order('tanggal',{ascending:false});if(error)return msg('newsList','Gagal: '+error.message,true);state.newsRows=data||[];$('newsList').innerHTML=rowsHTML(state.newsRows,'news')}
async function loadEvents(){const {data,error}=await db.from('kegiatan').select('*').order('tanggal',{ascending:false});if(error)return;$('eventList').innerHTML=rowsHTML(data||[],'events');state.eventRows=data||[]}
async function loadAwards(){const {data,error}=await db.from('prestasi').select('*').order('tahun',{ascending:false});if(error)return;$('awardList').innerHTML=rowsHTML(data||[],'awards');state.awardRows=data||[]}
async function loadAlumni(){const {data,error}=await db.from('alumni').select('*').order('tahun_lulus',{ascending:false}).order('nama');if(error)return;$('alumniList').innerHTML=rowsHTML(data||[],'alumni');state.alumniRows=data||[]}
window.loadNews=loadNews;window.loadEvents=loadEvents;window.loadAwards=loadAwards;window.loadAlumni=loadAlumni;window.loadGTK=loadGTK;
function formDate(v){return v?v.slice(0,10):''}function setMode(button,cancel,text){$(button).textContent=text;$(cancel).classList.remove('hidden')}function clearMode(button,cancel,text){$(button).textContent=text;$(cancel).classList.add('hidden')}
$('addNews').onclick=async()=>{const p={judul:$('newsTitle').value.trim(),tanggal:$('newsDate').value?new Date($('newsDate').value).toISOString():new Date().toISOString(),isi:$('newsBody').value.trim(),ringkasan:$('newsBody').value.trim().slice(0,180),penulis:state.user.email,published:true};if(!p.judul)return alert('Judul berita wajib diisi.');const q=state.news?db.from('berita').update(p).eq('id',state.news.id):db.from('berita').insert(p);const {error}=await q;if(error)return alert(error.message);resetNews();loadNews()};window.editNews=id=>{state.news=state.newsRows.find(x=>x.id===id);const x=state.news;if(!x)return;$('newsTitle').value=x.judul;$('newsDate').value=formDate(x.tanggal);$('newsBody').value=x.isi||'';setMode('addNews','cancelNews','💾 Simpan Perubahan');location.hash='berita'};function resetNews(){state.news=null;['newsTitle','newsDate','newsBody'].forEach(id=>$(id).value='');clearMode('addNews','cancelNews','➕ Tambah Berita')}$('cancelNews').onclick=resetNews;
$('addEvent').onclick=async()=>{const p={judul:$('eventTitle').value.trim(),tanggal:$('eventDate').value||null,lokasi:$('eventLocation').value.trim(),deskripsi:$('eventBody').value.trim()};if(!p.judul)return alert('Nama kegiatan wajib diisi.');const q=state.event?db.from('kegiatan').update(p).eq('id',state.event.id):db.from('kegiatan').insert(p);const {error}=await q;if(error)return alert(error.message);resetEvent();loadEvents()};window.editEvent=id=>{state.event=state.eventRows.find(x=>x.id===id);const x=state.event;if(!x)return;$('eventTitle').value=x.judul;$('eventDate').value=formDate(x.tanggal);$('eventLocation').value=x.lokasi||'';$('eventCategory').value='';$('eventBody').value=x.deskripsi||'';setMode('addEvent','cancelEvent','💾 Simpan Perubahan');location.hash='kegiatan'};function resetEvent(){state.event=null;['eventTitle','eventDate','eventLocation','eventCategory','eventBody'].forEach(id=>$(id).value='');clearMode('addEvent','cancelEvent','➕ Tambah Kegiatan')}$('cancelEvent').onclick=resetEvent;
$('addAward').onclick=async()=>{const p={judul:$('awardTitle').value.trim(),tahun:Number($('awardYear').value)||null,deskripsi:$('awardField').value.trim(),tingkat:$('awardLevel').value.trim()};if(!p.judul)return alert('Nama prestasi wajib diisi.');const q=state.award?db.from('prestasi').update(p).eq('id',state.award.id):db.from('prestasi').insert(p);const {error}=await q;if(error)return alert(error.message);resetAward();loadAwards()};window.editAward=id=>{state.award=state.awardRows.find(x=>x.id===id);const x=state.award;if(!x)return;$('awardTitle').value=x.judul;$('awardYear').value=x.tahun||'';$('awardField').value=x.deskripsi||'';$('awardLevel').value=x.tingkat||'';setMode('addAward','cancelAward','💾 Simpan Perubahan');location.hash='prestasi'};function resetAward(){state.award=null;['awardTitle','awardYear','awardField','awardLevel'].forEach(id=>$(id).value='');clearMode('addAward','cancelAward','➕ Tambah Prestasi')}$('cancelAward').onclick=resetAward;
$('addAlumni').onclick=async()=>{try{const file=$('alumniPhoto').files[0];let foto_url=state.alumni?.foto_url||null;if(file)foto_url=await upload('foto-alumni',file,'alumni');const p={nama:$('alumniName').value.trim(),tahun_lulus:Number($('alumniYear').value)||null,pekerjaan:$('alumniJob').value.trim(),pendidikan_lanjutan:$('alumniEdu').value.trim(),keterangan:$('alumniInfo').value.trim(),foto_url,aktif:true};if(!p.nama)return alert('Nama alumni wajib diisi.');const q=state.alumni?db.from('alumni').update(p).eq('id',state.alumni.id):db.from('alumni').insert(p);const {error}=await q;if(error)throw error;resetAlumni();loadAlumni()}catch(e){alert(e.message)}};window.editAlumni=id=>{state.alumni=state.alumniRows.find(x=>x.id===id);const x=state.alumni;if(!x)return;$('alumniName').value=x.nama;$('alumniYear').value=x.tahun_lulus||'';$('alumniJob').value=x.pekerjaan||'';$('alumniEdu').value=x.pendidikan_lanjutan||'';$('alumniInfo').value=x.keterangan||'';$('alumniPreview').src=x.foto_url||'';$('alumniPreview').style.display=x.foto_url?'block':'none';setMode('addAlumni','cancelAlumni','💾 Simpan Perubahan');location.hash='alumni'};function resetAlumni(){state.alumni=null;['alumniName','alumniYear','alumniJob','alumniEdu','alumniInfo','alumniPhoto'].forEach(id=>$(id).value='');$('alumniPreview').style.display='none';clearMode('addAlumni','cancelAlumni','➕ Tambah Alumni')}$('cancelAlumni').onclick=resetAlumni;
$('addGallery').onclick=async()=>{try{const file=$('galleryPhoto').files[0];if(!state.gallery&&!file)return alert('Foto wajib dipilih.');let foto_url=state.gallery?.foto_url||null;if(file)foto_url=await upload('galeri',file,'galeri');const p={judul:$('galleryTitle').value.trim(),deskripsi:$('galleryCategory').value.trim(),foto_url};if(!p.judul||!foto_url)return alert('Judul dan foto wajib diisi.');const q=state.gallery?db.from('galeri').update(p).eq('id',state.gallery.id):db.from('galeri').insert(p);const {error}=await q;if(error)throw error;resetGallery();loadGallery()}catch(e){alert(e.message)}};
async function loadGallery(){const {data,error}=await db.from('galeri').select('*').order('created_at',{ascending:false});if(error)return msg('galleryList','Gagal: '+error.message,true);state.galleryRows=data||[];$('galleryList').innerHTML=state.galleryRows.length?state.galleryRows.map(x=>`<div class="item"><div class="main"><img class="photo" src="${x.foto_url}" alt=""><div><b>${esc(x.judul)}</b><span class="small">${esc(x.deskripsi||'')}</span></div></div><div class="actions"><button class="blue" onclick="editGallery('${x.id}')">✏️ Edit</button><button class="danger" onclick="deleteRow('galeri','${x.id}',loadGallery)">🗑 Hapus</button></div></div>`).join(''):'<p class="small">Belum ada foto galeri.</p>'}
window.loadGallery=loadGallery;window.editGallery=id=>{state.gallery=state.galleryRows.find(x=>x.id===id);const x=state.gallery;if(!x)return;$('galleryTitle').value=x.judul;$('galleryCategory').value=x.deskripsi||'';$('galleryPreview').src=x.foto_url;$('galleryPreview').style.display='block';setMode('addGallery','cancelGallery','💾 Simpan Perubahan');location.hash='galeri'};function resetGallery(){state.gallery=null;['galleryTitle','galleryCategory','galleryPhoto'].forEach(id=>$(id).value='');$('galleryPreview').style.display='none';clearMode('addGallery','cancelGallery','➕ Tambah Foto')}$('cancelGallery').onclick=resetGallery;
window.deleteRow=async(table,id,reload)=>{if(!confirm('Hapus data ini?'))return;const {error}=await db.from(table).delete().eq('id',id);if(error)alert(error.message);else await reload()};
boot();
